exclude: "(^|/)data/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-yaml

  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.17.0
  #   hooks:
  #     - id: gitleaks
  #       args:
  #         - protect
  #         - --staged
  #         - --redact

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        #exclude: catalog_ingestor/src/resources
        args:
          - "--remove-all-unused-imports"
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
